### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8654/user-service/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.e

























































































































































































































































JzdWIiOiJrb25nbWluZyIsInJvbGUiOiJzdHVkZW50LGFkbWluIiwiaWF0IjoxNzU2MTM3ODAxLCJleHAiOjE3NTYxNDE0MDF9.NoS-oPYVsnFRRVSYVXDZM0tM43r8IXpyiuO_1THQqss